package com.group3.BilliardManagementSystem.Entity;


import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Pre-aggregated daily revenue snapshot per branch.
 *
 * Generated by a scheduled job (daily close-of-day) or on-demand.
 * Enables fast dashboard queries without re-aggregating raw invoice data.
 *
 * Also serves as structured input for AI/analytics pipelines —
 * export to CSV/Parquet for ML model training on revenue patterns.
 *
 * Design: one row per branch per date. Upsert on regeneration.
 */
@Entity
@Table(name = "revenue_report_logs",
    indexes = {
        @Index(name = "idx_rrl_branch_date", columnList = "branch_id, report_date", unique = true),
        @Index(name = "idx_rrl_report_date", columnList = "report_date")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RevenueReportLog extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "branch_id", nullable = false)
    private Branch branch;

    @Column(name = "report_date", nullable = false)
    private LocalDate reportDate;

    // --- Session Revenue ---
    @Column(name = "total_sessions", nullable = false)
    @Builder.Default
    private Integer totalSessions = 0;

    @Column(name = "total_play_minutes", nullable = false)
    @Builder.Default
    private Long totalPlayMinutes = 0L;

    @Column(name = "play_revenue", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal playRevenue = BigDecimal.ZERO;

    // --- F&B Revenue ---
    @Column(name = "total_orders", nullable = false)
    @Builder.Default
    private Integer totalOrders = 0;

    @Column(name = "fnb_revenue", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal fnbRevenue = BigDecimal.ZERO;

    // --- Total ---
    @Column(name = "gross_revenue", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal grossRevenue = BigDecimal.ZERO;

    @Column(name = "discount_total", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal discountTotal = BigDecimal.ZERO;

    @Column(name = "tax_total", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal taxTotal = BigDecimal.ZERO;

    @Column(name = "net_revenue", nullable = false, precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal netRevenue = BigDecimal.ZERO;

    // --- Payment Method Breakdown ---
    @Column(name = "cash_amount", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal cashAmount = BigDecimal.ZERO;

    @Column(name = "card_amount", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal cardAmount = BigDecimal.ZERO;

    @Column(name = "digital_wallet_amount", precision = 15, scale = 2)
    @Builder.Default
    private BigDecimal digitalWalletAmount = BigDecimal.ZERO;

    /** JSON blob for additional AI-ready metrics (e.g., peak hours, table utilization) */
    @Column(name = "extended_metrics", columnDefinition = "TEXT")
    private String extendedMetrics;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    @Builder.Default
    private ReportStatus status = ReportStatus.GENERATED;

    public enum ReportStatus {
        GENERATED, // Auto-generated by scheduler
        FINALIZED, // Manually reviewed and locked
        STALE      // Needs regeneration (data changed)
    }
}
