spring.datasource.url=jdbc:sqlserver://localhost:1434;databaseName=BilliardManagementDatabase;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=Sdt0366732074@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true